project:
  type: website
  output-dir: docs
website:
  title: "Hantavirus Data Analysis"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: Hantavirus_Research.html
        text: Hantavirus
      - href: resources.html
        text: Resources
format:
  html:
    theme: cosmo