project:
  type: website
  output-dir: docs

website:
  title: "Hantavirus Data Analysis"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: Hantavirus_Research.html
        text: Hantavirus

format:
  html:
    theme: cosmo
